[package]
name = "serial-direct-helloworld"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m-rt = "0.7.3"
panic-halt = "1.0.0"
defmt-rtt = "0.4.0"

[dependencies.microbit]
path = "../../microbit"
