[package]
name = "serial-direct-echo"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m-rt = "0.6.12"
panic-halt = "0.2.0"
defmt-rtt = "0.3.2"

[dependencies.microbit]
path = "../../microbit"
