[package]
name = "serial-hal-blocking-echo"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
defmt-rtt = "0.4"
nb = "1.0.0"
embedded-hal = "1.0.0"
embedded-io = "0.6.1"

[dependencies.microbit]
path = "../../microbit"
optional = true

[dependencies.microbit-v2]
path = "../../microbit-v2"
optional = true

[features]
v1 = ["microbit"]
v2 = ["microbit-v2"]
